name: Terraform plan and Apply

on:
  workflow_dispatch:
   
jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1        

      - name: Replace private key in main.tf
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > private_key.pem
          sed -i 's|###Private_key|'"$(cat private_key.pem)"'|g' main.tf

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: terraform plan
        run: terraform plan

      - name: terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve